from .facedetailer import (
    NODE_CLASS_MAPPINGS as FACE_DETAILER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FACE_DETAILER_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(FACE_DETAILER_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FACE_DETAILER_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
